-- create database db_petShop;
-- create table tb_animais
--  (
-- 	id bigint(20) auto_increment,
--  nome varchar(20) not null,
--  idade bigint(20),
--  sexo varchar(20),
--  raca varchar(20),
--  peso decimal(60,2),
--	primary key(id)
-- )

-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 1, "Feminino","Chiuaua", 10);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 2, "Feminino","Labrador", 5);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 3, "Feminino","golden", 15);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 4, "Feminino","labrador", 20);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 2, "Feminino","golden", 25);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 1, "Feminino","labrador", 5);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 5, "Feminino","labrador", 10);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 5, "Feminino","golden", 7);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 6, "Feminino","husky", 9);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Boris", 7, "Masculino","pinscher", 6);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 8, "Feminino","pinscher", 15);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 2, "Feminino","Labrador", 16);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 3, "Feminino","Golden", 14);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 4, "Feminino","Golden", 19);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 6, "Feminino","Golden", 20);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 3, "Feminino","Golden", 30);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 2, "Feminino","Golden", 40);
-- insert into tb_animais(nome, idade, sexo, raca, peso) Values ("Nina", 10, "Feminino","Golden", 50);

-- select * from tb_animais where nome like "%b%";
-- select * from tb_animais where peso > 20;
-- delete from tb_animais where id = 6;
-- update tb_animais set nome = "Maya" where id = 7;
